server:
  port: 8081



spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smartcane?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: smartcane
    password: smartcane123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update   # 개발: update / 운영: validate 권장
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul
  jackson:
    time-zone: Asia/Seoul

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 5b84cba18d5bc3aacc71b6a24afd06a0      # 카카오 REST API 키
            client-secret: 5MLUsjd01NlvJR2Lend29REnVYfJhV9u   # 보통 공란(필요 시 입력)
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: ["account_email","profile_nickname"]
            client-name: Kakao
          naver:
            client-id: EhsKoC7pYhbpE8M9QFWj
            client-secret: Mkt9yUNGjq
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: ["email","name","nickname"]
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri:         https://kauth.kakao.com/oauth/token
            user-info-uri:     https://kapi.kakao.com/v2/user/me
            user-name-attribute: id               # 카카오 고유 ID
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri:         https://nid.naver.com/oauth2.0/token
            user-info-uri:     https://openapi.naver.com/v1/nid/me
            user-name-attribute: response         # 최상위 키 'response' 내부의 id 사용

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

smartcane:
  jwt:
    issuer: smartcane-api
    # 운영 환경에서는 Base64 인코딩된 키를 환경변수로 주입하는 게 안전합니다.
    secret: ${JWT_SECRET:change-me-super-secret-32bytes-min}
    access-exp-seconds: 900        # Access Token 만료: 15분
    refresh-exp-seconds: 2592000   # Refresh Token 만료: 30일
    clock-skew-seconds: 60         # 허용 시간 오차(초)

  oauth2:
    # 성공 시 프론트(웹) 또는 앱 딥링크로 리다이렉트
    success-redirect: ${OAUTH_SUCCESS_REDIRECT:http://localhost:5173/auth/success}
    failure-redirect: ${OAUTH_FAILURE_REDIRECT:http://localhost:5173/auth/failure}
  fare:
    currency: KRW
    bus-fare: 1400
    subway-fare: 1550
    discounts:
      accessible-user-rate: 0.5
      subscription-rate: 0.0
    transfer:
      enabled: true
      window-minutes: 30      # 환승 유효 시간(분)
      max-transfers: 4        # 최대 환승 횟수(추가 탑승 수)
      pricing:
        type: FREE            # FREE | FLAT | RATIO
        flat-amount: 0        # type=FLAT 시, 환승 1회당 정액
        ratio: 0.0            # type=RATIO 시, 환승 1회당 원요금 대비 비율(예: 0.5 = 50%)

billing:
  api-base-url: https://api.tosspayments.com
  secret-key: sk_test_xxx123456789
  webhook:
    secret: whsec_test_yyy987654321